-- Translated names for daily theater
-- The id with ch0xxx follow conventional idol numbers
-- Nothing was changed except the name
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0001_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />호노카</span><br/><span size=""28"">" WHERE id = "petag_th_ch0001_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0002_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />에리</span><br/><span size=""28"">" WHERE id = "petag_th_ch0002_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0003_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />코토리</span><br/><span size=""28"">" WHERE id = "petag_th_ch0003_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0004_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />우미</span><br/><span size=""28"">" WHERE id = "petag_th_ch0004_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0005_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />린</span><br/><span size=""28"">" WHERE id = "petag_th_ch0005_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0006_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />마키</span><br/><span size=""28"">" WHERE id = "petag_th_ch0006_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0007_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />노조미</span><br/><span size=""28"">" WHERE id = "petag_th_ch0007_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0008_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />하나요</span><br/><span size=""28"">" WHERE id = "petag_th_ch0008_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0009_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />니코</span><br/><span size=""28"">" WHERE id = "petag_th_ch0009_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0101_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />치카</span><br/><span size=""28"">" WHERE id = "petag_th_ch0101_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0102_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />리코</span><br/><span size=""28"">" WHERE id = "petag_th_ch0102_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0103_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />카난</span><br/><span size=""28"">" WHERE id = "petag_th_ch0103_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0104_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />다이아</span><br/><span size=""28"">" WHERE id = "petag_th_ch0104_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0105_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />요우</span><br/><span size=""28"">" WHERE id = "petag_th_ch0105_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0106_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />요시코</span><br/><span size=""28"">" WHERE id = "petag_th_ch0106_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0107_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />하나마루</span><br/><span size=""28"">" WHERE id = "petag_th_ch0107_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0108_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />마리</span><br/><span size=""28"">" WHERE id = "petag_th_ch0108_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0109_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />루비</span><br/><span size=""28"">" WHERE id = "petag_th_ch0109_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0201_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />아유무</span><br/><span size=""28"">" WHERE id = "petag_th_ch0201_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0202_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />카스미</span><br/><span size=""28"">" WHERE id = "petag_th_ch0202_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0203_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />시즈쿠</span><br/><span size=""28"">" WHERE id = "petag_th_ch0203_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0204_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />카린</span><br/><span size=""28"">" WHERE id = "petag_th_ch0204_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0205_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />아이</span><br/><span size=""28"">" WHERE id = "petag_th_ch0205_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0206_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />카나타</span><br/><span size=""28"">" WHERE id = "petag_th_ch0206_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0207_dr0001_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />세츠나</span><br/><span size=""28"">" WHERE id = "petag_th_ch0207_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0208_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />베르데</span><br/><span size=""28"">" WHERE id = "petag_th_ch0208_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch9999_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />리나</span><br/><span size=""28"">" WHERE id = "petag_th_ch0209_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0210_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />시오리코</span><br/><span size=""28"">" WHERE id = "petag_th_ch0210_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0211_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />란쥬</span><br/><span size=""28"">" WHERE id = "petag_th_ch0211_empty";
UPDATE m_dictionary SET message = "<span size=""32""><img src=""Common/InlineImage/Member/tex_sd_ch0212_dr0003_01"" width=""88px"" height=""88px"" offsetY=""-25px"" />테일러</span><br/><span size=""28"">" WHERE id = "petag_th_ch0212_empty";